### ISSUE TITLE
Version 2.0.0

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem-atom-ui#2]
A backlog for the [Version 2.0.0](https://github.com/arcticicestudio/northem-atom-ui/milestone/1) milestone.
The whole project will be cleaned up and rewritten to adapt the codebase of the [Nord Atom UI](https://github.com/arcticicestudio/nord-atom-ui) project.

All sub-issues are listed below and will be merged into the main milestone branch [`release/ghi-#2-2.0.0`](https://github.com/arcticicestudio/northem-atom-ui/tree/release/ghi-%232-2.0.0).

  - [x] #5 [Northem 2.0.0](https://github.com/arcticicestudio/northem/releases/tag/v2.0.0) color palette update
  - [x] #3 Core component styles reimplementation
  - [x] #4 Package Support reimplementation
  - [x] #7 Nord Atom UI codebase migration
  - [x] #6 Adapt new project setup and documentation style

**Detailed information about new features can be found in the [Nord Atom UI](https://github.com/arcticicestudio/nord-atom-ui#features) documentations!**

### Color Palette
This major update will migrate to the new Northem color palette version [`2.0.0`](https://github.com/arcticicestudio/northem/releases/tag/v2.0.0).

### Design
The current design is uncomfortable, unconsistent and has not been updated to the latest Atom version which results in unpredictable bugs and glitch due to changes of the Atom Core.
Northem Atom UI will adapt the Nord Atom UI design which provides a clean, elegant and up-to-date UI.

### Package Support
All currently supported packages will be migrated to the new codebase and packages currently supported by Nord Atom UI will be added.

### Documentation
All project documentations will adapt the new project setup and styles.
