### ISSUE TITLE
Adapt new project setup and documentation style

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem-atom-ui#6]
**Tasks**
- [x] Refactor the `.gitignore` file
- [x] Clean up old project files
- [x] Update the to the new documentation style and move to the Apache 2.0 license
- [x] Add the new project branding assets (SVG and AI files)
- [x] Adapt Travis CI and Circle CI configurations

This issue is part of the [Version 2.0.0](https://github.com/arcticicestudio/northem-atom-ui/milestone/1) milestone trackined in the backlog issue #2.
