### ISSUE TITLE
Nord Atom UI codebase migration

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem-atom-ui#7]
:grey_exclamation: This issue **MUST BE** solved after #3, #4 and #5 :grey_exclamation: 

**Tasks**
  - [x] Replace old styles with new implemented styles
  - [x] Implement the theme settings feature
    - [x] Implement the `main.coffee` library
    - [x] Implement `specs`
    - [x] Implement config schema into the `package.json`

This issue is part of the [Version 2.0.0](https://github.com/arcticicestudio/northem-atom-ui/milestone/1) milestone trackined in the backlog issue #2.
